feat: check for minimum anvil version
ethereum-optimism/supersim pull request #47
Opened 2024-07-11 23:42 UTC by tremarkley

2024-07-11 23:42 UTC, tremarkley commented
* **#47** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/47?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tremarkley and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-12 13:45 UTC, jakim929 requested changes
foundry doesn't follow semver until 1.0.0 is released 
https://github.com/foundry-rs/foundry/blob/5b8416363c7c1aab6d3cda0da6e7c65594ad8a12/CHANGELOG.md

so 0.2.0 has been around for more than a year and covers a huge range of releases.

`foundryup` installs the latest nightly release. It might make more sense to check that the timestamp on the nightly release is past a certain minimum version.
`anvil 0.2.0 (0116be1 2024-07-09T00:18:45.485630000Z)`

Not sure what the minimum version we are trying to enforce is though.

2024-07-12 13:45 UTC, jakim929 commented on cmd/main.go
> +func isVersionGreaterOrEqual(version, minVersion string) bool {
nit: I think this package has the functionality you're looking for https://pkg.go.dev/golang.org/x/mod/semver
```
func Compare(v, w string)
```

2024-07-12 13:49 UTC, jakim929 commented on cmd/main.go
> +		return nil, fmt.Errorf("anvil version %s or higher is required.", minAnvilVersion)
nit: would be nice to also print `please use foundryup to update to the latest version

2024-07-12 15:20 UTC, jakim929 commented on cmd/main.go
> +func isVersionGreaterOrEqual(version, minVersion string) bool {
prob ignore this if we're not going with semver

2024-07-13 00:05 UTC, jakim929 approved these changes

2024-07-13 00:10 UTC, merged